import type { Metadata } from 'next'
import GlobalStyles from './styles/global'


export const metadata: Metadata = {
  title: 'Mobile phone payment terminal',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id="app">
        <GlobalStyles />
        {children}
      </body>
    </html>
  )
}
